apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi-jenkins
  name: fastapi-jenkins
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fastapi-jenkins
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-jenkins
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.k8.jevillanueva.dev
    secretName: fastapi-jenkins-tls
  rules:
  - host: api.k8.jevillanueva.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fastapi-jenkins
            port:
              number: 8000